<?php
//
// iTop module definition file
//

// The version below, the one in extension.xml and MCPHelper::VERSION are the
// same string. This file is read by the setup before the module's autoloader
// exists, so it cannot reference the constant; ModuleMetadataTest fails if the
// three ever drift apart. MCPHelper::VERSION documents the semver policy.
SetupWebPage::AddModule(
	__FILE__, // Path to the current file, all other file names are relative to the directory containing this file
	'altioo-mcp/1.0.0',
	array(
		// Identification
		//
		'label' => 'Altioo MCP iTop Extension',
		'category' => 'Application management',

		// Setup
		//
		'dependencies' => array(
			// The iTop floor, stated the only way the setup can enforce it:
			// extension.xml has no itop_version_min, so the branch is declared
			// through a core module that carries it. itop-structure is
			// mandatory in every installation, and a dependency with no
			// operator means ">=", so this reads "iTop 3.2 or later" and stops
			// the install on 3.1 with a legible message rather than a fatal
			// error somewhere inside a tool.
			'itop-structure/3.2.0',
			'authent-token/2.2.1',
		),
		'mandatory' => false,
		'visible' => true,

		// Components
		//
		'datamodel' => array(
			'vendor/autoload.php',
			'model.altioo-mcp.php', // Contains the PHP code generated by the "compilation" of datamodel.altioo-mcp.xml
			'register.php', // Contains the PHP code generated by the "compilation" of datamodel.altioo-mcp.xml
		),
		'webservice' => array (

		),
		'data.struct' => array(
			// add your 'structure' definition XML files here,
		),
		'data.sample' => array(
			// add your sample data XML files here,
		),

		// Documentation
		//
		// These two are the only links iTop shows next to the module once it is
		// installed, so an administrator who inherits the instance has
		// somewhere to go. The same documentation ships in the archive
		// (README.md and doc/), which is what answers the question offline.
		'doc.manual_setup' => 'https://github.com/altioo/mcp-server-extension/blob/main/README.md#installation',
		'doc.more_information' => 'https://github.com/altioo/mcp-server-extension/blob/main/README.md',

		// Default settings
		//
		'settings' => array(
			// Module specific settings go here, if any
		),
	)
);
