<?php
//
// iTop module definition file
//

// The version below, the one in extension.xml and MCPHelper::VERSION are the
// same string. This file is read by the setup before the module's autoloader
// exists, so it cannot reference the constant; ModuleMetadataTest fails if the
// three ever drift apart. MCPHelper::VERSION documents the semver policy.
SetupWebPage::AddModule(
	__FILE__, // Path to the current file, all other file names are relative to the directory containing this file
	'altioo-mcp/1.0.0',
	array(
		// Identification
		//
		'label' => 'Altioo MCP iTop Extension',
		'category' => 'Application management',

		// Setup
		//
		'dependencies' => array(
			'authent-token/2.2.1',
		),
		'mandatory' => false,
		'visible' => true,

		// Components
		//
		'datamodel' => array(
			'vendor/autoload.php',
			'model.altioo-mcp.php', // Contains the PHP code generated by the "compilation" of datamodel.altioo-mcp.xml
			'register.php', // Contains the PHP code generated by the "compilation" of datamodel.altioo-mcp.xml
		),
		'webservice' => array (

		),
		'data.struct' => array(
			// add your 'structure' definition XML files here,
		),
		'data.sample' => array(
			// add your sample data XML files here,
		),

		// Documentation
		//
		'doc.manual_setup' => '', // hyperlink to manual setup documentation, if any
		'doc.more_information' => '', // hyperlink to more information, if any

		// Default settings
		//
		'settings' => array(
			// Module specific settings go here, if any
		),
	)
);
